/*
 Generated by typeshare 1.13.4
*/

export interface CreateProjectBody {
  name: string
  path?: string
}

export interface CreateTabBody {
  project_id: string
  label?: string
  cmd?: string
  cwd?: string
}

export interface TabSummary {
  tab_id: string
  label: string
  cwd?: string
  /** "claude", "codex", or absent when no agent is running in this tab. */
  agent?: string
  /**
   * User-configured cmd override (from desktop $projects). Not the
   * running shell path.
   */
  cmd?: string
  /**
   * Last CWD observed via OSC 7, persisted across sessions on desktop.
   * Used as the fallback initial cwd when mobile subscribes to a
   * sleeping tab.
   */
  last_cwd?: string
  pinned?: boolean
  /**
   * Set to true when the user explicitly renamed on desktop. Blocks
   * OSC-title updates from overwriting the label; mobile should honour
   * the same semantics for the rename op in Phase B.
   */
  user_renamed?: boolean
  /**
   * True if a PtyHandle currently exists for this tab_id (tab is live
   * on desktop). False for "sleeping" tabs that exist in projects.json
   * but have not been visited yet this session.
   */
  is_spawned?: boolean
}

export interface ProjectSummary {
  project_id: string
  name: string
  path?: string
  pinned?: boolean
  is_expanded: boolean
  tabs: TabSummary[]
}

export interface RemoveProjectBody {
  project_id: string
}

export interface RemoveTabBody {
  project_id: string
  tab_id: string
}

export interface RenameProjectBody {
  project_id: string
  new_name: string
}

export interface RenameTabBody {
  project_id: string
  tab_id: string
  new_label: string
}

export interface ReorderTabsBody {
  project_id: string
  old_index: number
  new_index: number
}

export interface TabStateSummary {
  cwd?: string
  agent?: string
  git_branch?: string
  ports: number[]
}

/** Frames sent from a mobile client to the desktop server. */
export type ClientFrame =
  /**
   * First frame after the WebSocket connection upgrade. Carries the
   * bearer token the device received during pairing. The WSS server's
   * auth-stub (next sub-step) reads this and either replies with
   * `ServerFrame::AuthOk` or `AuthFail` and closes.
   */
  | {
      op: 'auth'
      body: {
        token: string
      }
    }
  /**
   * Begin streaming a tab fresh. Server replies with a
   * `ServerFrame::Snapshot` at the current seq, then a stream of
   * `ServerFrame::Bytes` frames as new PTY output arrives.
   */
  | {
      op: 'subscribe'
      body: {
        tab_id: string
        /**
         * How many lines of scrollback to include in the initial
         * snapshot. The server passes this to the sidecar's serialize
         * op.
         */
        scrollback: number
      }
    }
  /**
   * Reconnect to a previously-subscribed tab. If `last_seq + 1` is
   * still in the hub's ring buffer, the server replays the missed
   * bytes; otherwise it sends a fresh snapshot at the current seq
   * and a new starting counter.
   *
   * `last_seq` is a `u64` on the wire but typeshare emits the TS type
   * as `number` (via `serialized_as`). JavaScript numbers carry 53
   * bits of integer precision, which is roughly 285 years of
   * continuous 1 GB/s traffic — well beyond any realistic session
   * lifetime. The `serialized_as` attribute is typeshare's escape
   * hatch: typeshare's parser rejects raw `u64` by default; this
   * tells it to codegen as if the field were `u32` while leaving the
   * runtime type (and the JSON wire encoding) as `u64`.
   */
  | {
      op: 'resume'
      body: {
        tab_id: string
        scrollback: number
        last_seq: number
      }
    }
  | {
      op: 'unsubscribe'
      body: {
        tab_id: string
      }
    }
  /**
   * User input — text the desktop should write to the PTY. Bracketed
   * paste wrapping (if any) happens on the desktop side before the
   * write hits the PTY.
   */
  | {
      op: 'write'
      body: {
        tab_id: string
        data: string
      }
    }
  | {
      op: 'resize'
      body: {
        tab_id: string
        cols: number
        rows: number
      }
    }
  /**
   * Protocol-level liveness probe. Server replies with
   * `ServerFrame::Pong`. Runs alongside WebSocket-level pings; this
   * higher layer catches "socket is fine but the app-level handler
   * is stuck" cases.
   */
  | { op: 'ping'; body?: undefined }
  | {
      op: 'create_project'
      body: {
        op_id: number
        body: CreateProjectBody
      }
    }
  | {
      op: 'create_tab'
      body: {
        op_id: number
        body: CreateTabBody
      }
    }
  | {
      op: 'rename_project'
      body: {
        op_id: number
        body: RenameProjectBody
      }
    }
  | {
      op: 'rename_tab'
      body: {
        op_id: number
        body: RenameTabBody
      }
    }
  | {
      op: 'remove_project'
      body: {
        op_id: number
        body: RemoveProjectBody
      }
    }
  | {
      op: 'remove_tab'
      body: {
        op_id: number
        body: RemoveTabBody
      }
    }
  /**
   * Reorder a tab within a project by index. Matches the desktop's
   * existing `$projects.reorderTabs(oldIdx, newIdx)` shape so the
   * mobile-ops listener maps 1:1.
   */
  | {
      op: 'reorder_tabs'
      body: {
        op_id: number
        body: ReorderTabsBody
      }
    }

/** Frames sent from the desktop server to a mobile client. */
export type ServerFrame =
  | {
      op: 'auth_ok'
      body: {
        device_name: string
      }
    }
  | {
      op: 'auth_fail'
      body: {
        reason: string
      }
    }
  /**
   * Project + tab tree push. Sent immediately after `AuthOk` and
   * again whenever the desktop's tab inventory changes (open, close,
   * respawn).
   */
  | {
      op: 'projects'
      body: {
        data: ProjectSummary[]
      }
    }
  /**
   * xterm-serialize output for `tab_id` at seq `seq`. `payload` is a
   * UTF-8 string of ANSI escape sequences the client replays into a
   * fresh xterm.js Terminal to restore visual state.
   */
  | {
      op: 'snapshot'
      body: {
        tab_id: string
        seq: number
        payload: string
      }
    }
  /**
   * One chunk of raw PTY output. `data` is base64-encoded because the
   * bytes are arbitrary binary; the client decodes base64 → bytes
   * before feeding xterm.js.
   */
  | {
      op: 'bytes'
      body: {
        tab_id: string
        seq: number
        data: string
      }
    }
  | {
      op: 'resized'
      body: {
        tab_id: string
        cols: number
        rows: number
      }
    }
  /**
   * Condensed per-tab metadata used for status pills on the mobile
   * UI. Pushed on subscribe and on any change.
   */
  | {
      op: 'tab_state'
      body: {
        tab_id: string
        state: TabStateSummary
      }
    }
  | {
      op: 'pty_exit'
      body: {
        tab_id: string
      }
    }
  | {
      op: 'pty_respawned'
      body: {
        tab_id: string
        cwd: string
      }
    }
  | { op: 'pong'; body?: undefined }
  /**
   * A mobile-originated CRUD op failed. `op_id` echoes the client's
   * correlation id so the sender can reject the matching pending
   * promise. The next `Projects` push does NOT arrive after an
   * OpError (React never applied the mutation).
   */
  | {
      op: 'op_error'
      body: {
        op_id: number
        reason: string
      }
    }
  /**
   * A mobile-originated CRUD op succeeded. `op_id` echoes the client's
   * correlation id so the sender can resolve the matching pending
   * promise. The next `Projects` push arrives immediately after so
   * the client also observes the mutation in state.
   */
  | {
      op: 'op_ok'
      body: {
        op_id: number
      }
    }
