/*
 Generated by typeshare 1.13.4
*/

export interface TabSummary {
  tab_id: string
  label: string
  cwd?: string
  /** "claude", "codex", or absent when no agent is running in this tab. */
  agent?: string
}

export interface ProjectSummary {
  project_id: string
  name: string
  tabs: TabSummary[]
}

export interface TabStateSummary {
  cwd?: string
  agent?: string
  git_branch?: string
  ports: number[]
}

/** Frames sent from a mobile client to the desktop server. */
export type ClientFrame =
  /**
   * First frame after the WebSocket connection upgrade. Carries the
   * bearer token the device received during pairing. The WSS server's
   * auth-stub (next sub-step) reads this and either replies with
   * `ServerFrame::AuthOk` or `AuthFail` and closes.
   */
  | {
      op: 'auth'
      body: {
        token: string
      }
    }
  /**
   * Begin streaming a tab fresh. Server replies with a
   * `ServerFrame::Snapshot` at the current seq, then a stream of
   * `ServerFrame::Bytes` frames as new PTY output arrives.
   */
  | {
      op: 'subscribe'
      body: {
        tab_id: string
        /**
         * How many lines of scrollback to include in the initial
         * snapshot. The server passes this to the sidecar's serialize
         * op.
         */
        scrollback: number
      }
    }
  /**
   * Reconnect to a previously-subscribed tab. If `last_seq + 1` is
   * still in the hub's ring buffer, the server replays the missed
   * bytes; otherwise it sends a fresh snapshot at the current seq
   * and a new starting counter.
   *
   * `last_seq` is a `u64` on the wire but typeshare emits the TS type
   * as `number` (via `serialized_as`). JavaScript numbers carry 53
   * bits of integer precision, which is roughly 285 years of
   * continuous 1 GB/s traffic — well beyond any realistic session
   * lifetime. The `serialized_as` attribute is typeshare's escape
   * hatch: typeshare's parser rejects raw `u64` by default; this
   * tells it to codegen as if the field were `u32` while leaving the
   * runtime type (and the JSON wire encoding) as `u64`.
   */
  | {
      op: 'resume'
      body: {
        tab_id: string
        scrollback: number
        last_seq: number
      }
    }
  | {
      op: 'unsubscribe'
      body: {
        tab_id: string
      }
    }
  /**
   * User input — text the desktop should write to the PTY. Bracketed
   * paste wrapping (if any) happens on the desktop side before the
   * write hits the PTY.
   */
  | {
      op: 'write'
      body: {
        tab_id: string
        data: string
      }
    }
  | {
      op: 'resize'
      body: {
        tab_id: string
        cols: number
        rows: number
      }
    }
  /**
   * Protocol-level liveness probe. Server replies with
   * `ServerFrame::Pong`. Runs alongside WebSocket-level pings; this
   * higher layer catches "socket is fine but the app-level handler
   * is stuck" cases.
   */
  | { op: 'ping'; body?: undefined }

/** Frames sent from the desktop server to a mobile client. */
export type ServerFrame =
  | {
      op: 'auth_ok'
      body: {
        device_name: string
      }
    }
  | {
      op: 'auth_fail'
      body: {
        reason: string
      }
    }
  /**
   * Project + tab tree push. Sent immediately after `AuthOk` and
   * again whenever the desktop's tab inventory changes (open, close,
   * respawn).
   */
  | {
      op: 'projects'
      body: {
        data: ProjectSummary[]
      }
    }
  /**
   * xterm-serialize output for `tab_id` at seq `seq`. `payload` is a
   * UTF-8 string of ANSI escape sequences the client replays into a
   * fresh xterm.js Terminal to restore visual state.
   */
  | {
      op: 'snapshot'
      body: {
        tab_id: string
        seq: number
        payload: string
      }
    }
  /**
   * One chunk of raw PTY output. `data` is base64-encoded because the
   * bytes are arbitrary binary; the client decodes base64 → bytes
   * before feeding xterm.js.
   */
  | {
      op: 'bytes'
      body: {
        tab_id: string
        seq: number
        data: string
      }
    }
  | {
      op: 'resized'
      body: {
        tab_id: string
        cols: number
        rows: number
      }
    }
  /**
   * Condensed per-tab metadata used for status pills on the mobile
   * UI. Pushed on subscribe and on any change.
   */
  | {
      op: 'tab_state'
      body: {
        tab_id: string
        state: TabStateSummary
      }
    }
  | {
      op: 'pty_exit'
      body: {
        tab_id: string
      }
    }
  | {
      op: 'pty_respawned'
      body: {
        tab_id: string
        cwd: string
      }
    }
  | { op: 'pong'; body?: undefined }
